#!/usr/bin/php
<?php

require_once('scripts.settings.php');
main($argv);

function main($argv) {
  $conf = _scripts_conf($argv);
  
  $version = $conf->version;
  $drupal_version = $conf->drupal_version;
  $my_profile = $conf->my_profile;
  $profile_name = $conf->profile_name;
  $path = $conf->path;
  $docroot = $conf->docroot;
  $profile = $conf->profile;
  $build_make = $conf->build_make;

  $commands = array(
    sprintf('git clone --recursive --branch %s %s', $conf->branch, $conf->repo),
    sprintf('mv %s/.git %s/', $conf->my_profile, $conf->profile),
    sprintf('rm -rf %s', $conf->my_profile),
    sprintf("cd %s; %s;\n", $conf->profile, 'git reset --hard'),
    sprintf('rm %s/.gitignore', $conf->profile),
  );
  foreach($commands as $command) {
    execute_command($command);
  }

  // Rebuild project on 7.x-1.x-dev.
  echo "To rebuild install profile, do this:\n";
  echo "\t" . "cd $conf->profile\n";
  echo "\t" . 'rm -Rf modules/contrib themes/ libraries' . "\n";
  echo "\t" . 'drush -y make --no-core --contrib-destination=. drupal-org.make' . "\n";
}

/**
 * Execute command and print results.
 * 
 * @param $command
 *  String. Command to be run from the command line.
 */
function execute_command($command) {
  echo "\nRunning:\n\t$command\n";
  shell_exec($command);
  // $result = exec($command, $output);
  // printf("result: %s\n\n", print_r($result));
  // printf("output: %s\n\n", print_r($output));
}
