#!/usr/bin/php
<?php

require_once('scripts.settings.php');
main($argv);

function main($argv) {
  $conf = _scripts_conf($argv);

  $module_path = $conf->profile . '/modules/contrib/lessons';
  $commands = array(
    'git clone --recursive --branch 7.x-1.x bhirsch@git.drupal.org:project/lessons.git',
    "mv lessons/.git $module_path",
    'rm -rf lessons',
    sprintf('rm %s/.gitignore', $module_path),
    sprintf("cd %s; %s;\n", $module_path, 'git reset --hard'),
  );
  foreach($commands as $command) {
    execute_command($command);
  }
}

/**
 * Execute command and print results.
 * 
 * @param $command
 *  String. Command to be run from the command line.
 */
function execute_command($command) {
  echo "\nRunning:\n\t$command\n";
  shell_exec($command);
  // $result = exec($command, $output);
  // printf("result: %s\n\n", print_r($result));
  // printf("output: %s\n\n", print_r($output));
}
